on:
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      credentials: ${{ secrets.secret_credentials }}
    steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        - run: |
            chmod +x test.sh
            ./test.sh
